apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-root-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://github.com/Melyenn/yas-gitops.git" # Repo chứa cấu hình GitOps (thư mục hiện tại)
    targetRevision: main
    path: .
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
