# values-dev.yaml
domain: "yas.local.com"
envTag: "dev-13"
namespace: "yas-dev"
infraNamespace: "yas-13"
repoURL: "https://github.com/BongLanTrungMuoi/yas-CI-CD.git"
targetRevision: main
coreServices:
  - cart
  - customer
  - inventory
  - media
  - order
  - product
  - search
  - tax
# Default image tags for dev
global:
  image:
    tag: "latest"
# Cấu hình riêng cho từng service nếu cần (để phục vụ developer_build)
services:
  yas-configuration: {tag: "latest"}
  backoffice-bff: {tag: "209ae12"}
  backoffice-ui: {tag: "latest"}
  storefront-bff: {tag: "209ae12"}
  storefront-ui: {tag: "latest"}
  swagger-ui: {tag: "latest"}
  cart: {tag: "latest"}
  customer: {tag: "209ae12"}
  inventory: {tag: "209ae12"}
  media: {tag: "c39e860"}
  order: {tag: "latest"}
  product: {tag: "latest"}
  search: {tag: "209ae12"}
  tax: {tag: "latest"}
  location:
    tag: latest
  payment:
    tag: latest
  promotion:
    tag: latest
  rating:
    tag: latest
  recommendation:
    tag: latest
  webhook:
    tag: latest
  sampledata:
    tag: latest
  delivery:
    tag: latest
