# values-dev.yaml
domain: "yas.local.com"
envTag: "${ENV_TAG}"
namespace: "yas-dev"
infraNamespace: "${YAS_NAMESPACE}"
repoURL: "https://github.com/BongLanTrungMuoi/yas-CI-CD.git"
targetRevision: main

coreServices:
  - cart
  - customer
  - inventory
  - location
  - media
  - order
  - payment
  - product
  - promotion
  - rating
  - search
  - tax
  - recommendation
  - webhook
  - sampledata

# Default image tags for dev
global:
  image:
    tag: "latest"

# Cấu hình riêng cho từng service nếu cần (để phục vụ developer_build)
services:
  yas-configuration: { tag: "latest" }
  backoffice-bff: { tag: "latest" }
  backoffice-ui: { tag: "latest" }
  storefront-bff: { tag: "latest" }
  storefront-ui: { tag: "latest" }
  swagger-ui: { tag: "latest" }
  cart: { tag: "latest" }
  customer: { tag: "latest" }
  inventory: { tag: "latest" }
  location: { tag: "latest" }
  media: { tag: "latest" }
  order: { tag: "latest" }
  payment: { tag: "latest" }
  product: { tag: "latest" }
  promotion: { tag: "latest" }
  rating: { tag: "latest" }
  search: { tag: "latest" }
  tax: { tag: "latest" }
  recommendation: { tag: "latest" }
  webhook: { tag: "latest" }
  sampledata: { tag: "latest" }
